# Generated by Django 2.2 on 2019-06-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190529_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='image/IMG_3232.JPG', upload_to='images/'),
        ),
    ]
