# Generated by Django 2.2 on 2019-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190601_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='children',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
